# Définir la sortie par défaut
log4j.rootLogger=INFO, stdout

# Ajouter un appender console
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d %-5p [%c] %m%n

# (optionnel) catégorie spécifique pour Velocity
log4j.logger.my.fr.velocity.category=DEBUG